/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketmachine;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author Radu
 */
public class PurchaseTicket extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseTicket
     */
    //Objects that help in calling methods from other classes
    Miscellaneous miscellaneous = new Miscellaneous();
    //Class attributes
    String titleFinal = "", dayFinal = "", hoursFinal = "", adult = "", senior = "", student = "";

    //Constructor that receives strings as parameters from TicketMachine class
    public PurchaseTicket(String title, String day, String hours) {
        setContentPane(new JLabel(new ImageIcon("purchaseticket.jpg")));
        initComponents();
        setTitle("Purchase Ticket");
        setLocationRelativeTo(null);
        titleFinal = title;
        dayFinal = day;
        hoursFinal = hours;
        txtMovieName.setText(title);
        txtMovieDay.setText(day);
        txtMovieHours.setText(hours);
        //Disabling the text fields from the number pickers
        ((JSpinner.DefaultEditor) npAdult.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) npSenior.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) npStudent.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelectTickets = new javax.swing.JLabel();
        lblAdult = new javax.swing.JLabel();
        lblSenior = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        npAdult = new javax.swing.JSpinner();
        npSenior = new javax.swing.JSpinner();
        npStudent = new javax.swing.JSpinner();
        btnSave = new javax.swing.JButton();
        txtMovieName = new javax.swing.JTextField();
        txtMovieDay = new javax.swing.JTextField();
        txtMovieHours = new javax.swing.JTextField();
        lblStudentPrice = new javax.swing.JLabel();
        lblAdultPrice = new javax.swing.JLabel();
        lblSeniorPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelectTickets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectTickets.setText("SELECT TICKETS");
        getContentPane().add(lblSelectTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 13, 270, -1));

        lblAdult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdult.setText("Adult");
        getContentPane().add(lblAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 150, 50, 30));

        lblSenior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenior.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenior.setText("Senior");
        getContentPane().add(lblSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 190, 50, 30));

        lblStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStudent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudent.setText("Student");
        getContentPane().add(lblStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 30));

        npAdult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        npAdult.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(npAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 80, 30));

        npSenior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        npSenior.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(npSenior, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 80, 30));

        npStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        npStudent.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        getContentPane().add(npStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 80, 30));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 150, 40));

        txtMovieName.setEditable(false);
        txtMovieName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMovieName.setText("TITLE");
        txtMovieName.setFocusable(false);
        getContentPane().add(txtMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 149, -1));

        txtMovieDay.setEditable(false);
        txtMovieDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMovieDay.setText("DAY");
        txtMovieDay.setFocusable(false);
        getContentPane().add(txtMovieDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 149, -1));

        txtMovieHours.setEditable(false);
        txtMovieHours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieHours.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMovieHours.setText("HOUR");
        txtMovieHours.setFocusable(false);
        getContentPane().add(txtMovieHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 149, -1));

        lblStudentPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblStudentPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStudentPrice.setText("Student: 3");
        getContentPane().add(lblStudentPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        lblAdultPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAdultPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdultPrice.setText("Adult: 5");
        getContentPane().add(lblAdultPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 70, -1));

        lblSeniorPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSeniorPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeniorPrice.setText("Senior: 4");
        getContentPane().add(lblSeniorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Price:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Statement that checks if the user has selected at least one ticket
        if (!npAdult.getValue().equals(0) || !npSenior.getValue().equals(0) || !npStudent.getValue().equals(0)) {
            adult = npAdult.getValue().toString();
            senior = npSenior.getValue().toString();
            student = npStudent.getValue().toString();
            TicketMachine ticketMachine = new TicketMachine(titleFinal, dayFinal, hoursFinal, adult, senior, student, "");
            ticketMachine.setVisible(true);
            miscellaneous.correct_click();
            this.dispose();
        } else {
            lblSelectTickets.setText("Select at least one ticket!");
            miscellaneous.error_click();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseTicket("", "", "").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdult;
    private javax.swing.JLabel lblAdultPrice;
    private javax.swing.JLabel lblSelectTickets;
    private javax.swing.JLabel lblSenior;
    private javax.swing.JLabel lblSeniorPrice;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblStudentPrice;
    private javax.swing.JSpinner npAdult;
    private javax.swing.JSpinner npSenior;
    private javax.swing.JSpinner npStudent;
    private javax.swing.JTextField txtMovieDay;
    private javax.swing.JTextField txtMovieHours;
    private javax.swing.JTextField txtMovieName;
    // End of variables declaration//GEN-END:variables
}
