/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketmachine;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Radu
 */
public class ShowPayment extends javax.swing.JFrame {

    /**
     * Creates new form ShowPayment
     */
    //Objects that help in calling methods from other classes
    Miscellaneous miscellaneous = new Miscellaneous();
    //Class attributes
    int adultNumber = 0, seniorNumber = 0, studentNumber = 0;
    double adultPrice = 0, seniorPrice = 0, studentPrice = 0, totalSum = 0;
    String titleFinal, dayFinal, hoursFinal, adultFinal, seniorFinal, studentFinal, totalSumFinal;

    //Constructor that receives strings as parameters from TicketMachine class
    public ShowPayment(String title, String day, String hours, String adult, String senior, String student) {
        setContentPane(new JLabel(new ImageIcon("showpayment.jpg")));
        initComponents();
        setTitle("Show Payment");
        setLocationRelativeTo(null);
        txtMovieName.setText(title);
        txtMovieDay.setText(day);
        txtMovieHour.setText(hours);
        //Converting String into int for calculus
        adultNumber = Integer.parseInt(adult);
        seniorNumber = Integer.parseInt(senior);
        studentNumber = Integer.parseInt(student);
        txtAdults.setText(adult);
        txtSeniors.setText(senior);
        txtStudents.setText(student);
        //Setting the standard price and discounted ones
        adultPrice = 5;
        seniorPrice = 0.8 * adultPrice;
        studentPrice = 0.6 * adultPrice;
        //Total sum calculation
        totalSum = adultNumber * adultPrice + seniorNumber * seniorPrice + studentNumber * studentPrice;
        txtTotalSum.setText(String.valueOf(totalSum));
        btnSave.setVisible(false);
        btnExit.setVisible(false);
        titleFinal = title;
        dayFinal = day;
        hoursFinal = hours;
        adultFinal = adult;
        seniorFinal = senior;
        studentFinal = student;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFinalReceipt = new javax.swing.JLabel();
        lblMovieDay = new javax.swing.JLabel();
        txtMovieName = new javax.swing.JTextField();
        lblAdults = new javax.swing.JLabel();
        lblSeniors = new javax.swing.JLabel();
        lblStudents = new javax.swing.JLabel();
        txtAdults = new javax.swing.JTextField();
        txtSeniors = new javax.swing.JTextField();
        txtStudents = new javax.swing.JTextField();
        lblTotalSum = new javax.swing.JLabel();
        lblTotalSum1 = new javax.swing.JLabel();
        txtTotalSum = new javax.swing.JTextField();
        txtCashSum = new javax.swing.JTextField();
        lblChange = new javax.swing.JLabel();
        txtChange = new javax.swing.JTextField();
        lblMovieHour = new javax.swing.JLabel();
        lblMovieName = new javax.swing.JLabel();
        txtMovieDay = new javax.swing.JTextField();
        txtMovieHour = new javax.swing.JTextField();
        btnInsertMoney = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFinalReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFinalReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalReceipt.setText("PAYMENT");
        getContentPane().add(lblFinalReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 310, -1));

        lblMovieDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMovieDay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMovieDay.setText("Day");
        getContentPane().add(lblMovieDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtMovieName.setEditable(false);
        txtMovieName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMovieName.setText("YOUR MOVIE NAME");
        txtMovieName.setFocusable(false);
        txtMovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 183, -1));

        lblAdults.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAdults.setText("ADULTS");
        getContentPane().add(lblAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        lblSeniors.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblSeniors.setText("SENIORS");
        getContentPane().add(lblSeniors, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, 20));

        lblStudents.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblStudents.setText("STUDENTS");
        getContentPane().add(lblStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, 20));

        txtAdults.setEditable(false);
        txtAdults.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAdults.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAdults.setFocusable(false);
        getContentPane().add(txtAdults, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 30, -1));

        txtSeniors.setEditable(false);
        txtSeniors.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSeniors.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSeniors.setFocusable(false);
        getContentPane().add(txtSeniors, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 30, -1));

        txtStudents.setEditable(false);
        txtStudents.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStudents.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStudents.setFocusable(false);
        getContentPane().add(txtStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 30, -1));

        lblTotalSum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTotalSum.setText("TOTAL SUM");
        getContentPane().add(lblTotalSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        lblTotalSum1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTotalSum1.setText("CASH SUM");
        getContentPane().add(lblTotalSum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, -1));

        txtTotalSum.setEditable(false);
        txtTotalSum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalSum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalSum.setFocusable(false);
        getContentPane().add(txtTotalSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        txtCashSum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCashSum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCashSum.setText("INSERT HERE");
        txtCashSum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCashSumMouseClicked(evt);
            }
        });
        txtCashSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashSumActionPerformed(evt);
            }
        });
        getContentPane().add(txtCashSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, -1));

        lblChange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblChange.setText("CHANGE");
        lblChange.setToolTipText("");
        getContentPane().add(lblChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 280, -1));

        txtChange.setEditable(false);
        txtChange.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChange.setText("-");
        txtChange.setFocusable(false);
        getContentPane().add(txtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, -1));

        lblMovieHour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMovieHour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMovieHour.setText("Hour");
        getContentPane().add(lblMovieHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblMovieName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMovieName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMovieName.setText("Movie");
        getContentPane().add(lblMovieName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtMovieDay.setEditable(false);
        txtMovieDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieDay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMovieDay.setText("YOUR MOVIE DAY");
        txtMovieDay.setFocusable(false);
        txtMovieDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieDayActionPerformed(evt);
            }
        });
        getContentPane().add(txtMovieDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 183, -1));

        txtMovieHour.setEditable(false);
        txtMovieHour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMovieHour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMovieHour.setText("YOUR MOVIE HOUR");
        txtMovieHour.setFocusable(false);
        txtMovieHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovieHourActionPerformed(evt);
            }
        });
        getContentPane().add(txtMovieHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 183, -1));

        btnInsertMoney.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertMoney.setText("INSERT MONEY");
        btnInsertMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertMoneyActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 203, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("SAVE AND GET CHANGE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("EXIT TO MENU");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 203, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieNameActionPerformed

    private void txtMovieDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieDayActionPerformed

    private void txtMovieHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovieHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovieHourActionPerformed

    private void btnInsertMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertMoneyActionPerformed
        //Try-catch statement that verifies the input and if statements that check the difference between total sum and cash sum
        try {
            lblFinalReceipt.setText("Payment");
            double cashSum = Double.parseDouble(txtCashSum.getText());
            double change = Math.round((totalSum - cashSum) * 100.0) / 100.0;

            if (change < 0) {
                change = -change;
            }
            if (totalSum < cashSum) {
                txtChange.setText(String.valueOf(change));
                btnSave.setVisible(true);
                btnInsertMoney.setVisible(false);
                txtCashSum.setVisible(false);
                lblTotalSum1.setText("CASH: " + String.valueOf(cashSum));
                miscellaneous.correct_click();
            } else if (totalSum > cashSum) {
                txtChange.setText("INSERT " + String.valueOf(change));
                btnSave.setVisible(false);
                miscellaneous.error_click();
            } else {
                txtChange.setText("OK");
                btnSave.setVisible(true);
                btnInsertMoney.setVisible(false);
                txtCashSum.setVisible(false);
                txtChange.setVisible(false);
                lblChange.setVisible(false);
                lblTotalSum1.setText("CASH: " + String.valueOf(cashSum));
                miscellaneous.correct_click();
            }
        } catch (Exception e) {
            lblFinalReceipt.setText("Please enter numbers!");
            miscellaneous.error_click();
        }
    }//GEN-LAST:event_btnInsertMoneyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //Event that saves the user input
        lblTotalSum1.setText("INVOICE VALUE: " + String.valueOf(totalSum));
        txtChange.setVisible(false);
        btnInsertMoney.setVisible(false);
        btnExit.setVisible(true);
        btnSave.setVisible(false);
        lblChange.setVisible(true);
        lblChange.setText("Now you can print the receipt from Menu!");
        miscellaneous.correct_click();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //Event that opens a main menu window and closes the current one
        totalSumFinal = String.valueOf(totalSum);
        TicketMachine ticketMachine = new TicketMachine(titleFinal, dayFinal, hoursFinal, adultFinal, seniorFinal, studentFinal, totalSumFinal);
        ticketMachine.setVisible(true);
        miscellaneous.correct_click();
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtCashSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashSumActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCashSumActionPerformed

    private void txtCashSumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCashSumMouseClicked
        //Emptying the text box
        if (txtCashSum.getText().equals("INSERT HERE")) {
            txtCashSum.setText("");
        }
    }//GEN-LAST:event_txtCashSumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPayment("", "", "", "", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsertMoney;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAdults;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblFinalReceipt;
    private javax.swing.JLabel lblMovieDay;
    private javax.swing.JLabel lblMovieHour;
    private javax.swing.JLabel lblMovieName;
    private javax.swing.JLabel lblSeniors;
    private javax.swing.JLabel lblStudents;
    private javax.swing.JLabel lblTotalSum;
    private javax.swing.JLabel lblTotalSum1;
    private javax.swing.JTextField txtAdults;
    private javax.swing.JTextField txtCashSum;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtMovieDay;
    private javax.swing.JTextField txtMovieHour;
    private javax.swing.JTextField txtMovieName;
    private javax.swing.JTextField txtSeniors;
    private javax.swing.JTextField txtStudents;
    private javax.swing.JTextField txtTotalSum;
    // End of variables declaration//GEN-END:variables
}
